--- This is a deck of card
fmod CARD-DECK is
    sorts Number Suit Card .
    ops A 2 3 4 5 6 7 8 9 10 J Q K : -> Number [ctor] .
    ops Clubs Diamonds Hearts Spades : -> Suit [ctor] .
    op _of_ : Number Suit -> Card [ctor] .
    op CardNum : Card -> Number .
    op CardSuit : Card -> Suit .
    var N : Number .
    var S : Suit .
    eq CardNum ( N of S ) = N .
    eq CardSuit ( N of S ) = S .
endfm